### ISSUE TITLE
Unable to build assimp2xml3D

### ISSUE THREAD

**Issue by nikolasbe** [csvurt/assimp2xml3d#4]
I am unable to build assimp2xml3D (on Ubuntu 14.04) because the installation keeps asking me to build with -fPIC, however that doesn't resolve anything either.

This is the error:

> [ 79%] Building CXX object assimp/code/CMakeFiles/assimp.dir/__/contrib/openddlparser/code/Value.cpp.o
> Linking CXX shared library ../../lib/libassimp.so
> /usr/bin/ld: ../../lib/libzlibstatic.a(compress.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
> ../../lib/libzlibstatic.a: error adding symbols: Bad value
> collect2: error: ld returned 1 exit status
> make[2]: **\* [lib/libassimp.so.3.1.1] Error 1
> make[1]: **\* [assimp/co

Would you have to happen a Windows executable (W10) lying around?

**Comment by csvurt** [comment]
Hi,

have you tried the 0.2 executable in the [releases?](https://github.com/csvurt/assimp2xml3d/releases) It should work on W10. 

Your build error seems to happen during the building of Assimp so it might be best to ask them about it over in their [Github repo](https://github.com/assimp/assimp), maybe they can find a solution for you. You could also try updating the assimp and tinyxml submodules with `git submodule foreach git pull`, maybe they've already fixed the build problem remotely.

**Comment by nikolasbe** [comment]
Hi, thanks for you quick reply, looked over the releases! Thanks!
